field: b67271c9-deaf-4f52-91f6-3392469feae8 # Blokken
fieldLayouts:
  6a2ac407-274e-464d-823e-8629b22030a8:
    tabs:
      -
        elements:
          -
            fieldUid: 329c0d61-58cc-4ee2-812a-6ebb31e692db # Kaarten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  329c0d61-58cc-4ee2-812a-6ebb31e692db: # Kaarten
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cards
    instructions: ''
    name: Kaarten
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 47aa44f4-b258-43f0-92f9-08513110dafe # Titel
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 830901d7-ab4c-4d50-984d-f87a5bf654e4 # Tekst
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 67f52e00-c9f8-4fa7-bcc6-2ff6635b0338 # Inhoud
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_21_cards}}'
      fieldLayout: row
      maxRows: ''
      minRows: '1'
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: contentCards
name: 'Content kaarten'
sortOrder: 4
