field: b67271c9-deaf-4f52-91f6-3392469feae8 # Blokken
fieldLayouts:
  1a755b39-d806-4b3f-8514-3444e27c50a3:
    tabs:
      -
        elements:
          -
            fieldUid: 9e06c017-f04d-4615-b6d9-44512bdb1ce9 # Achtergrondkleur
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 680a557c-6175-4cb6-a397-b3b42c540c50 # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57d2d210-c613-4648-a626-5d5235c40234 # Inhoud
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9e06c017-f04d-4615-b6d9-44512bdb1ce9: # Achtergrondkleur
    columnSuffix: caxnychv
    contentColumnType: text
    fieldGroup: null
    handle: backgroundColor
    instructions: ''
    name: Achtergrondkleur
    searchable: false
    settings:
      allowCustomColor: false
      allowCustomColorPicker: false
      allowOpacity: false
      colorFormat: auto
      defaultColorHandle: ''
      defaultOpacity: '100'
      fieldDescriptions: false
      paletteBaseColors: null
      paletteColors: ''
      presetId: '1'
      presetMode: false
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\colorit\fields\ColoritField
  57d2d210-c613-4648-a626-5d5235c40234: # Inhoud
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: ''
    name: Inhoud
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:c7a73282-02b4-4b76-854d-58c24ede0f81' # Vragen
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  680a557c-6175-4cb6-a397-b3b42c540c50: # Titel
    columnSuffix: yefrnooq
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: faqBlock
name: 'Veelgestelde vragen'
sortOrder: 16
