field: 22c9b66e-8ed9-4067-9fb9-e02a1f250d7f # Footer content
fieldLayouts:
  b0dc745b-2c8c-42a0-b666-99b20ddb2ffc:
    tabs:
      -
        elements:
          -
            fieldUid: 99fd912f-77bb-4658-bd5d-80ca9e924d6b # Footer Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 5edc4b85-b143-4f76-b60d-3c0c0605587e # Footer Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
        name: Content
        sortOrder: 1
fields:
  5edc4b85-b143-4f76-b60d-3c0c0605587e: # Footer Tekst
    columnSuffix: roazrjmz
    contentColumnType: text
    fieldGroup: null
    handle: footerText
    instructions: ''
    name: 'Footer Tekst'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  99fd912f-77bb-4658-bd5d-80ca9e924d6b: # Footer Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: footerLogo
    instructions: ''
    name: 'Footer Logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:553c5ad6-3250-4b4b-a8fa-37f35373494d' # Assets
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:553c5ad6-3250-4b4b-a8fa-37f35373494d' # Assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: footerContent
name: 'Footer Content'
sortOrder: 1
