field: b67271c9-deaf-4f52-91f6-3392469feae8 # Blokken
fieldLayouts:
  0adba29d-a0b1-48e2-a8d2-b432b47be0c1:
    tabs:
      -
        elements:
          -
            fieldUid: 7dbcf101-5d5d-4016-865a-51bad730e4d9 # Achtergrondkleur
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 1bf4b387-f78b-4efc-84b4-e409f6423c65 # Indeling
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d011f1fe-4b18-493b-99e3-269298156fa7 # Afbeelding Desktop
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b23eaf87-5f8d-46e7-a03e-b9f82dcbbfaa # Afbeelding Mobiel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0ff30834-7192-492f-90f2-a8401510d82f # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 602bdc3e-5843-4879-85a7-cf27071d8737 # Tekst
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 09b89905-ed73-4faf-9c33-b6c461c6310f # CTA's
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0ff30834-7192-492f-90f2-a8401510d82f: # Titel
    columnSuffix: auetffyo
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1bf4b387-f78b-4efc-84b4-e409f6423c65: # Indeling
    columnSuffix: zasalijg
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: ''
    name: Indeling
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Afbeelding Rechts'
            -
              - value
              - image-right
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Afbeelding Links'
            -
              - value
              - image-left
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  7dbcf101-5d5d-4016-865a-51bad730e4d9: # Achtergrondkleur
    columnSuffix: cwqrpqzw
    contentColumnType: text
    fieldGroup: null
    handle: backgroundColor
    instructions: ''
    name: Achtergrondkleur
    searchable: false
    settings:
      allowCustomColor: false
      allowCustomColorPicker: false
      allowOpacity: false
      colorFormat: auto
      defaultColorHandle: ''
      defaultOpacity: '100'
      fieldDescriptions: false
      paletteBaseColors: null
      paletteColors: ''
      presetId: '2'
      presetMode: false
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\colorit\fields\ColoritField
  09b89905-ed73-4faf-9c33-b6c461c6310f: # CTA's
    columnSuffix: tsgtqcph
    contentColumnType: string
    fieldGroup: null
    handle: ctas
    instructions: ''
    name: 'CTA''s'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - d87a3d70-0e27-4f32-87d4-afea07d924d0 # CTA
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_13_ctas}}'
      fieldLayout: row
      maxRows: '2'
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  602bdc3e-5843-4879-85a7-cf27071d8737: # Tekst
    columnSuffix: wrwzyrwe
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b23eaf87-5f8d-46e7-a03e-b9f82dcbbfaa: # Afbeelding Mobiel
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageMobile
    instructions: ''
    name: 'Afbeelding Mobiel'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:553c5ad6-3250-4b4b-a8fa-37f35373494d' # Assets
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:553c5ad6-3250-4b4b-a8fa-37f35373494d' # Assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d011f1fe-4b18-493b-99e3-269298156fa7: # Afbeelding Desktop
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageDesktop
    instructions: ''
    name: 'Afbeelding Desktop'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:553c5ad6-3250-4b4b-a8fa-37f35373494d' # Assets
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:553c5ad6-3250-4b4b-a8fa-37f35373494d' # Assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: textImageBlock
name: 'Tekst en afbeelding'
sortOrder: 14
