fieldLayouts:
  086c69c8-ea46-44f0-9980-257b6d548a71:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1e05ab99-5320-4492-b9b5-7df4b11fdc00 # Vraag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf4cd569-d0b6-49eb-bebb-d6f789757455 # Antwoord
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: question
hasTitleField: false
name: Vraag
section: c7a73282-02b4-4b76-854d-58c24ede0f81 # Vragen
sortOrder: 1
titleFormat: '{question}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
