defaultPlacement: end
fieldLayouts:
  a0bcc824-d698-4bbc-b91c-efe3202fcf49:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 50
          -
            fieldUid: 163f8077-5e22-4216-a8dc-96c62b8cc736 # Kaart Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 63284e79-c995-4800-a887-532736269464 # Uitgelichte afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 164de2f6-4bc7-49ea-b902-5b259249fab9 # CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: subjects
name: Onderwerpen
siteSettings:
  c3dd2df9-188d-4590-ac87-62318e5eb486: # KNZB
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: bbbdea16-39fe-499d-8862-fe94f28f75f3
