columnSuffix: null
contentColumnType: string
fieldGroup: 62bdff2d-64e6-4b21-8d1a-e63f9b794dc5 # Common
handle: blocks
instructions: ''
name: Blokken
searchable: false
settings:
  contentTable: '{{%matrixcontent_blocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
