columnSuffix: vhukrnka
contentColumnType: text
fieldGroup: 2ab79f8e-9122-47ec-b6f9-4d096c939b10 # Meta
handle: cardTitle
instructions: ''
name: 'Kaart Titel'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
