columnSuffix: dznyjqwx
contentColumnType: text
fieldGroup: 62bdff2d-64e6-4b21-8d1a-e63f9b794dc5 # Common
handle: cta
instructions: ''
name: CTA
searchable: false
settings:
  allowCustomText: ''
  allowTarget: '1'
  defaultText: ''
  selectLinkText: ''
  types:
    __assoc__:
      -
        - presseddigital\linkit\models\Email
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Phone
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Url
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
            -
              - allowAlias
              - '1'
            -
              - allowMailto
              - '1'
            -
              - allowHash
              - '1'
            -
              - allowPaths
              - '1'
      -
        - presseddigital\linkit\models\Twitter
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Facebook
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Instagram
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\LinkedIn
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Entry
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\Category
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\Asset
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\User
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
            -
              - userPath
              - ''
translationKeyFormat: null
translationMethod: none
type: presseddigital\linkit\fields\LinkitField
