columnSuffix: null
contentColumnType: string
fieldGroup: 05631174-aab0-4a97-a8e6-bb9ad45da0e1 # Heroes
handle: detailHero
instructions: ''
name: 'Detail Hero'
searchable: false
settings:
  contentTable: '{{%matrixcontent_detailhero}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
