columnSuffix: null
contentColumnType: string
fieldGroup: 89aafaee-869a-4a60-864b-bae48f3fa269 # Globals
handle: modals
instructions: ''
name: Modals
searchable: false
settings:
  contentTable: '{{%matrixcontent_modals}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
