columnSuffix: null
contentColumnType: string
fieldGroup: 62bdff2d-64e6-4b21-8d1a-e63f9b794dc5 # Common
handle: overviewSettings
instructions: ''
name: 'Overzicht settings'
searchable: false
settings:
  contentTable: '{{%matrixcontent_overviewsettings}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
