handle: sportForm
name: 'Sport Forms'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: true
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: 99
template: _form/sportForm
useCustomTemplates: true
